# Generated by Django 5.0.7 on 2024-09-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='C:/Program Files/Tencent/WeChat/WeChat.exe', max_length=255,
                                          verbose_name='WeChat Path')),
                ('locale', models.CharField(default='zh-CN', max_length=10, verbose_name='Locale')),
            ],
        ),
    ]
