# Generated by Django 5.x on 2024-10-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=64)),
                ("endpoint", models.CharField(blank=True, default="", max_length=128)),
                ("status", models.CharField(choices=[("received", "received"), ("queued", "queued"), ("running", "running"), ("success", "success"), ("failed", "failed")], default="received", max_length=16)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("client_ip", models.CharField(blank=True, default="", max_length=64)),
            ],
        ),
    ]

