# Generated by Django 5.0.7 on 2024-09-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='C:/Program Files/Tencent/Weixin/Weixin.exe', help_text='微信 4.x 可执行文件路径，通常为 Weixin.exe。', max_length=255, verbose_name='WeChat Path')),
                ('locale', models.CharField(default='zh-CN', max_length=10, verbose_name='Locale')),
                ('search_pages', models.PositiveIntegerField(default=5, help_text='会话列表搜索页数。')),
                ('send_delay', models.FloatField(default=0.2, help_text='发送消息/文件时的单次延迟（秒）。')),
                ('is_maximize', models.BooleanField(default=False, help_text='微信主窗口是否全屏。')),
                ('window_size', models.CharField(default='1000,1000', help_text='窗口大小，格式为 "宽,高"，例如 "1000,1000"。', max_length=32)),
                ('auto_start_wechat', models.BooleanField(default=True, help_text='若微信未启动，服务端是否尝试自动拉起 Weixin.exe。')),
            ],
        ),
    ]
