# Generated by Django 5.x on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_app", "0002_requestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="wechatconfig",
            name="auto_thank_after_red_packet",
            field=models.BooleanField(default=False, help_text="领取红包成功后，是否自动发送感谢消息。"),
        ),
        migrations.AddField(
            model_name="wechatconfig",
            name="red_packet_thanks_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="成功领取红包后发送给客户的感谢消息模板。支持 {friend} 或 {name} 占位符。",
            ),
        ),
    ]
