# Generated by Django 5.x on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_app", "0003_wechatconfig_red_packet_thanks"),
    ]

    operations = [
        migrations.AddField(
            model_name="wechatconfig",
            name="payment_reply_delay",
            field=models.FloatField(default=2.0, help_text="领取红包/转账后自动发送感谢消息前的等待时间（秒）。"),
        ),
    ]
