# Generated by Django 5.x on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_app", "0004_wechatconfig_payment_reply_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="wechatconfig",
            name="auto_payment_check_interval_minutes",
            field=models.FloatField(default=2.0, help_text="自动领取红包/转账的未读消息检查间隔（分钟）。"),
        ),
    ]
