# Generated by Django 4.1 on 2024-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_wechatuser_remove_message_username_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='wechatid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
