# Generated by Django 4.1 on 2024-07-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_alter_wechatuser_wechatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
