# Generated by Django 4.1 on 2024-07-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_serverconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
