# Generated by Django 4.1 on 2024-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_scheduledmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
