# Generated by Django 4.1 on 2024-07-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_remove_message_group_wechatuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='execution_skip',
            field=models.IntegerField(default=0),
        ),
    ]
