# Generated by Django 4.1 on 2024-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_alter_scheduledmessage_cron_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
