# Generated by Django 4.1 on 2024-08-01 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0015_log_input_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='input_params',
        ),
    ]
