# Generated by Django 4.1 on 2024-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0018_emailsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsettings',
            old_name='from_email',
            new_name='default_from_email',
        ),
        migrations.RenameField(
            model_name='emailsettings',
            old_name='auth_password',
            new_name='email_host_password',
        ),
        migrations.RenameField(
            model_name='emailsettings',
            old_name='auth_user',
            new_name='email_host_user',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='email_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
