# Generated by Django 4.1 on 2024-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0019_rename_from_email_emailsettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host',
            field=models.CharField(default='smtp.163.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_port',
            field=models.IntegerField(default=25),
        ),
    ]
