# Generated by Django 4.1 on 2024-08-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0020_alter_emailsettings_email_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='email_use_tls',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='email_security',
            field=models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL')], default='tls', max_length=3),
        ),
    ]
