# Generated by Django 4.1 on 2024-08-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0022_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
