# Generated by Django 4.1 on 2024-09-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0024_errorlog_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='default_from_email',
            field=models.EmailField(help_text='发送邮件的邮箱，一般也是email_host_user', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host',
            field=models.CharField(default='smtp.163.com', help_text='邮箱主机地址', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host_password',
            field=models.CharField(help_text='邮箱密码（这里一般是授权码，请自行申请）', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host_user',
            field=models.CharField(help_text='邮箱用户名', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_port',
            field=models.IntegerField(default=25, help_text='邮箱主机端口'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_security',
            field=models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL')], default='tls', help_text='安全协议选择', max_length=3),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='recipient_list',
            field=models.TextField(help_text='收件人邮箱列表，用逗号分隔'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='emailed',
            field=models.BooleanField(default=False, help_text='错误是否已通过邮件发送'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_detail',
            field=models.TextField(help_text='错误的详细描述'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_type',
            field=models.CharField(help_text='错误的类型', max_length=255),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='task_id',
            field=models.CharField(blank=True, help_text='相关任务的 ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='错误日志创建的时间'),
        ),
        migrations.AlterField(
            model_name='log',
            name='function_name',
            field=models.CharField(help_text='调用的函数名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='input_params',
            field=models.TextField(default='null', help_text='函数的输入参数，JSON 字符串'),
        ),
        migrations.AlterField(
            model_name='log',
            name='result',
            field=models.BooleanField(help_text='函数调用的结果，成功为 True，失败为 False'),
        ),
        migrations.AlterField(
            model_name='log',
            name='return_data',
            field=models.TextField(default='null', help_text='函数的返回数据'),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='日志创建的时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='发送消息'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(help_text='关联的微信用户', on_delete=django.db.models.deletion.CASCADE, to='client_app.wechatuser'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='cron_expression',
            field=models.CharField(help_text='定时任务的 cron 表达式', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='execution_count',
            field=models.IntegerField(default=0, help_text='任务执行的次数'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='execution_skip',
            field=models.IntegerField(default=0, help_text='任务被跳过的次数'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否激活该定时消息'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='last_executed',
            field=models.DateTimeField(blank=True, help_text='任务上次执行的时间', null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='text',
            field=models.TextField(help_text='定时发送的消息内容'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='user',
            field=models.ForeignKey(help_text='关联的微信用户', on_delete=django.db.models.deletion.CASCADE, to='client_app.wechatuser'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='server_ip',
            field=models.CharField(help_text='服务器的IP地址', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='date_added',
            field=models.DateTimeField(blank=True, help_text='用户添加的日期', null=True),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='group',
            field=models.CharField(blank=True, help_text='用户分组', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='username',
            field=models.CharField(help_text='微信用户的用户名', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='wechatid',
            field=models.CharField(blank=True, help_text='微信用户的微信ID', max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MessageCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='检测规则是否激活')),
                ('keyword', models.CharField(help_text='检测的关键词', max_length=255)),
                ('cron_expression', models.CharField(help_text='用于定时检测的 cron 表达式', max_length=255)),
                ('message_count', models.IntegerField(default=10, help_text='要检测的最近消息数目')),
                ('report_on_found', models.BooleanField(default=True, help_text='如果为 True，则在检测到关键词时报错；否则在未检测到时报错')),
                ('execution_count', models.IntegerField(default=0, help_text='任务执行的次数')),
                ('execution_skip', models.IntegerField(default=0, help_text='跳过执行的次数')),
                ('last_checked', models.DateTimeField(blank=True, help_text='上次检测的时间', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_checks', to='client_app.wechatuser')),
            ],
        ),
    ]
