# Generated by Django 5.1.1 on 2024-09-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0025_alter_emailsettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagecheck',
            name='execution_count',
        ),
        migrations.RemoveField(
            model_name='messagecheck',
            name='execution_skip',
        ),
        migrations.AlterField(
            model_name='messagecheck',
            name='user',
            field=models.ForeignKey(help_text='关联的微信用户', on_delete=django.db.models.deletion.CASCADE, related_name='message_checks', to='client_app.wechatuser'),
        ),
    ]
