# Generated by Django 5.1.1 on 2024-09-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_app', '0026_remove_messagecheck_execution_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecheck',
            name='use_time_blocks',
            field=models.BooleanField(default=False,
                                      help_text='如果为 True，则 message_count 代表时间分组的个数；如果为 False，则 message_count 代表消息条数'),
        ),
        migrations.AlterField(
            model_name='messagecheck',
            name='keyword',
            field=models.CharField(help_text='检测的关键词/正则表达式', max_length=255),
        ),
        migrations.AlterField(
            model_name='messagecheck',
            name='message_count',
            field=models.IntegerField(default=10, help_text='要检测的最近消息数目或时间分组的数量'),
        ),
    ]
