# Generated by Django 4.1 on 2024-10-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_app', '0027_messagecheck_use_time_blocks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledFileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该定时文件消息')),
                ('file_path', models.CharField(help_text='定时发送的文件路径', max_length=1024)),
                ('cron_expression', models.CharField(help_text='定时任务的 cron 表达式', max_length=255)),
                ('execution_count', models.IntegerField(default=0, help_text='任务执行的次数')),
                ('execution_skip', models.IntegerField(default=0, help_text='任务被跳过的次数')),
                ('last_executed', models.DateTimeField(blank=True, help_text='任务上次执行的时间', null=True)),
                ('user', models.ForeignKey(help_text='关联的微信用户', on_delete=django.db.models.deletion.CASCADE,
                                           to='client_app.wechatuser')),
            ],
        ),
    ]
