# Generated by Django 5.1.1 on 2025-08-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0029_customscript_alter_scheduledfilemessage_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='任务的名称', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='任务执行的时间')),
                ('status', models.CharField(help_text="任务执行的状态 (e.g., 'success', 'failure')", max_length=50)),
                ('details', models.TextField(blank=True, help_text='任务执行的详细信息或输出', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
