# Generated by Django 4.1 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0030_tasklog_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='备份文件保留天数')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='配置更新时间')),
            ],
        ),
    ]
