name: Client_Push Docker image

on:
  release:
    types: [created]

jobs:
  build-and-test-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./YuYuWechatV2_Client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: image=moby/buildkit:buildx-stable-1

    - name: Build Docker image
      run: docker build -t yuyuwechatv2_client .

    - name: Run Docker container
      run: docker run -d -p 7500:7500 --name yuyuwechatv2_client-container yuyuwechatv2_client

    - name: Wait for the server to start
      run: sleep 10

    - name: Display Docker logs
      run: docker logs yuyuwechatv2_client-container

    - name: Test main endpoint
      run: curl --fail http://127.0.0.1:7500

    - name: Test admin endpoint
      run: curl --fail http://127.0.0.1:7500/admin

    - name: Test send_message_management endpoint
      run: curl --fail http://127.0.0.1:7500/send_message_management/

    - name: Test schedule_management endpoint
      run: curl --fail http://127.0.0.1:7500/schedule_management/

    - name: Stop and remove Docker container
      run: docker rm -f yuyuwechatv2_client-container

    - name: Save Docker image to tar file
      run: docker save yuyuwechatv2_client -o yuyuwechatv2_client.tar

    - name: Compress Docker image tar file
      run: gzip yuyuwechatv2_client.tar

    - name: Modify permissions of the compressed file
      run: chmod 777 yuyuwechatv2_client.tar.gz

    - name: Check generated files and permissions
      run: |
        ls -lh
        ls -lh yuyuwechatv2_client.tar.gz

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /home/runner/work/YuYuWechatV2/YuYuWechatV2/YuYuWechatV2_Client/yuyuwechatv2_client.tar.gz
        asset_name: yuyuwechatv2_client.tar.gz
        asset_content_type: application/gzip

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /home/runner/work/YuYuWechatV2/YuYuWechatV2/YuYuWechatV2_Client/docker-compose.yml
        asset_name: docker-compose.yml
        asset_content_type: application/yaml


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./YuYuWechatV2_Client
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/yuyuwechatv2_client:latest
          ${{ secrets.DOCKER_USERNAME }}/yuyuwechatv2_client:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64